{% set name = "qtwayland" %}
{% set version = "6.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
  sha256: e710e6e760f92922b86e4dd68f6bbe94ef6510919519d1b0068e874b5ad84d37
  patches:
    # Fix get_target_property() called with non-existent target "Qt6::WaylandGlobalPrivate" -> Qt's build system expects
    # WaylandGlobalPrivate to already be available when qt_internal_add_module() runs.
    - patches/0001-Add-find_package-before-qt_internal_add_module.patch
    - patches/0002-Fix-internal-target-exports-in-Wayland-modules.patch

build:
  number: 1
  skip: true  # [not linux]
  detect_binary_files_with_prefix: true
  # https://doc.qt.io/qt-6/qt-releases.html#binary-compatibility
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base
    - perl
  host:
    # https://doc.qt.io/qt-6/wayland-requirements.html
    - qtbase-devel {{ version }}
    - qtdeclarative {{ version }}
    - qtsvg {{ version }}
    - wayland {{ wayland }}
    - libegl-devel {{ libgl }}
    - libglx-devel {{ libglx }}
    - libopengl-devel {{ libopengl }}
    - libvulkan-headers {{ libvulkan }}
    - libvulkan-loader {{ libvulkan }}
    - libxkbcommon {{ libxkbcommon }}

test:
  commands:
    {% set qt_libs = ["WaylandCompositor"] %}
    {% for each_qt_lib in qt_libs %}
    - test -d $PREFIX/include/qt6/Qt{{ each_qt_lib }}  # [unix]
    - test -f $PREFIX/lib/libQt6{{ each_qt_lib }}${SHLIB_EXT}  # [unix]
    {% endfor %}

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/GFDL-1.3-no-invariants-only.txt
    - LICENSES/GPL-2.0-only.txt
    - LICENSES/GPL-3.0-only.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-Qt-Commercial.txt
    - LICENSES/Qt-GPL-exception-1.0.txt
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    The QtWayland module consists of two parts.

    Wayland platform plugin --
        Enables Qt applications to be run as Wayland clients.

    QtWaylandCompositor API --
        Enables the creation of Wayland compositors using Qt and QtQuick.
  doc_url: https://doc.qt.io/qt-6/wayland-and-qt.html
  dev_url: https://github.com/qt/{{ name }}

extra:
  feedstock-name: qt-wayland
  recipe-maintainers:
    - hmaarrfk
