{% set name = "qtwayland" %}
{% set version = "6.9.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/{{ name }}-everywhere-src-{{ version }}.tar.xz
  sha256: cad79806565568f12f9983fed69219416abcee9d5deef4abdfcf94aa2eef7781

build:
  number: 0
  skip: true  # [not linux]
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - perl
  host:
    # https://doc.qt.io/qt-6/wayland-requirements.html
    - qtbase-devel {{ version }}
    - qtdeclarative {{ version }}
    - qtsvg {{ version }}
    - wayland {{ wayland }}
    - libegl-devel {{ libgl }}
    - libglx-devel {{ libglx }}
    - libopengl-devel {{ libopengl }}
    - libvulkan-headers {{ libvulkan }}
    - libvulkan-loader {{ libvulkan }}
    - libxkbcommon {{ libxkbcommon }}
  run_constrained:
    - qt-main >={{ version }},<7
    - qt >={{ version }},<7

test:
  commands:
    {% set qt_libs = ["WaylandClient", "WaylandCompositor"] %}
    {% for each_qt_lib in qt_libs %}
    - test -d $PREFIX/include/qt6/Qt{{ each_qt_lib }}  # [unix]
    - test -f $PREFIX/lib/libQt6{{ each_qt_lib }}${SHLIB_EXT}  # [unix]
    {% endfor %}

about:
  home: https://www.qt.io/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file:
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/GFDL-1.3-no-invariants-only.txt
    - LICENSES/GPL-2.0-only.txt
    - LICENSES/GPL-3.0-only.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-Qt-Commercial.txt
    - LICENSES/Qt-GPL-exception-1.0.txt
  summary: Cross-platform application and UI framework ({{ name[2:] }} libraries).
  description: |
    The QtWayland module consists of two parts.

    Wayland platform plugin --
        Enables Qt applications to be run as Wayland clients.

    QtWaylandCompositor API --
        Enables the creation of Wayland compositors using Qt and QtQuick.
  doc_url: https://doc.qt.io/qt-6/wayland-and-qt.html
  dev_url: https://github.com/qt/{{ name }}

extra:
  feedstock-name: qt-wayland
  recipe-maintainers:
    - hmaarrfk
